import { Member, Event, Partner, Stat, Testimonial, FAQ } from './types';

export const sampleMembers: Member[] = [
  {
    id: '1',
    name: 'Ahmad Razif',
    role: 'Core Team Lead',
    company: 'Superteam MY',
    bio: 'Leading the Solana ecosystem growth in Malaysia. Building bridges between Web2 and Web3.',
    photo_url: '/images/members/placeholder.jpg',
    twitter_url: 'https://x.com/superteammy',
    skill_tags: ['Core Team', 'Growth', 'Community'],
    achievements: { hackathon_wins: 3, projects_built: 5, grants_received: 2 },
    is_featured: true,
    is_core_team: true,
    display_order: 1,
    created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'Sarah Chen',
    role: 'Frontend Engineer',
    company: 'SolanaFM',
    bio: 'Building beautiful DeFi interfaces. React & Solana enthusiast.',
    photo_url: '/images/members/placeholder.jpg',
    twitter_url: 'https://x.com/superteammy',
    skill_tags: ['Frontend', 'Design', 'Rust'],
    achievements: { hackathon_wins: 2, projects_built: 8, bounties_completed: 15 },
    is_featured: true,
    is_core_team: false,
    display_order: 2,
    created_at: '2024-02-01',
  },
  {
    id: '3',
    name: 'Raj Kumar',
    role: 'Solana Developer',
    company: 'Independent',
    bio: 'Full-stack Solana developer. Anchor & Rust specialist.',
    photo_url: '/images/members/placeholder.jpg',
    twitter_url: 'https://x.com/superteammy',
    skill_tags: ['Rust', 'Frontend', 'Product'],
    achievements: { hackathon_wins: 5, projects_built: 12, grants_received: 3 },
    is_featured: true,
    is_core_team: false,
    display_order: 3,
    created_at: '2024-03-01',
  },
  {
    id: '4',
    name: 'Mei Ling Tan',
    role: 'Content Lead',
    company: 'Superteam MY',
    bio: 'Crafting narratives for the Malaysian Web3 ecosystem.',
    photo_url: '/images/members/placeholder.jpg',
    twitter_url: 'https://x.com/superteammy',
    skill_tags: ['Content', 'Growth', 'Community'],
    achievements: { bounties_completed: 20, projects_built: 3 },
    is_featured: true,
    is_core_team: true,
    display_order: 4,
    created_at: '2024-01-15',
  },
  {
    id: '5',
    name: 'Daniel Lim',
    role: 'Product Designer',
    company: 'Jupiter',
    bio: 'Designing the future of DeFi. Passionate about Web3 UX.',
    photo_url: '/images/members/placeholder.jpg',
    twitter_url: 'https://x.com/superteammy',
    skill_tags: ['Design', 'Product', 'Frontend'],
    achievements: { hackathon_wins: 1, projects_built: 6 },
    is_featured: false,
    is_core_team: false,
    display_order: 5,
    created_at: '2024-04-01',
  },
  {
    id: '6',
    name: 'Nurul Aina',
    role: 'BizDev Manager',
    company: 'Marinade Finance',
    bio: 'Connecting Solana projects with Malaysian enterprises.',
    photo_url: '/images/members/placeholder.jpg',
    twitter_url: 'https://x.com/superteammy',
    skill_tags: ['Growth', 'Community', 'Product'],
    achievements: { projects_built: 4, dao_contributions: 8 },
    is_featured: false,
    is_core_team: false,
    display_order: 6,
    created_at: '2024-05-01',
  },
];

export const sampleEvents: Event[] = [
  {
    id: '1',
    title: 'Solana Builder Night KL',
    description: 'A night of building, networking, and learning about the latest in Solana development.',
    date: '2025-03-15T18:00:00',
    location: 'Kuala Lumpur, Malaysia',
    luma_url: 'https://lu.ma/superteammy',
    image_url: '/images/events/placeholder.jpg',
    is_upcoming: true,
    created_at: '2025-01-01',
  },
  {
    id: '2',
    title: 'Web3 Hackathon Malaysia',
    description: 'Build the next big thing on Solana. $50K in prizes.',
    date: '2025-04-20T09:00:00',
    location: 'Penang, Malaysia',
    luma_url: 'https://lu.ma/superteammy',
    image_url: '/images/events/placeholder.jpg',
    is_upcoming: true,
    created_at: '2025-01-15',
  },
  {
    id: '3',
    title: 'DeFi Deep Dive Workshop',
    description: 'Learn how to build DeFi protocols on Solana from scratch.',
    date: '2025-05-10T14:00:00',
    location: 'Virtual',
    luma_url: 'https://lu.ma/superteammy',
    image_url: '/images/events/placeholder.jpg',
    is_upcoming: true,
    created_at: '2025-02-01',
  },
  {
    id: '4',
    title: 'Superteam MY Launch Party',
    description: 'The official launch of Superteam Malaysia with keynotes from global leaders.',
    date: '2024-12-01T19:00:00',
    location: 'Kuala Lumpur, Malaysia',
    luma_url: 'https://lu.ma/superteammy',
    image_url: '/images/events/placeholder.jpg',
    is_upcoming: false,
    created_at: '2024-11-01',
  },
];

export const samplePartners: Partner[] = [
  { id: '1', name: 'Solana Foundation', logo_url: '/images/partners/solana.svg', website_url: 'https://solana.com', category: 'solana_project', display_order: 1 },
  { id: '2', name: 'Jupiter', logo_url: '/images/partners/jupiter.svg', website_url: 'https://jup.ag', category: 'solana_project', display_order: 2 },
  { id: '3', name: 'Marinade', logo_url: '/images/partners/marinade.svg', website_url: 'https://marinade.finance', category: 'solana_project', display_order: 3 },
  { id: '4', name: 'Helius', logo_url: '/images/partners/helius.svg', website_url: 'https://helius.dev', category: 'solana_project', display_order: 4 },
  { id: '5', name: 'Raydium', logo_url: '/images/partners/raydium.svg', website_url: 'https://raydium.io', category: 'solana_project', display_order: 5 },
  { id: '6', name: 'Magic Eden', logo_url: '/images/partners/magiceden.svg', website_url: 'https://magiceden.io', category: 'solana_project', display_order: 6 },
  { id: '7', name: 'MDEC', logo_url: '/images/partners/mdec.svg', website_url: 'https://mdec.my', category: 'malaysian_partner', display_order: 7 },
  { id: '8', name: 'Cradle Fund', logo_url: '/images/partners/cradle.svg', website_url: 'https://cradle.com.my', category: 'malaysian_partner', display_order: 8 },
];

export const sampleStats: Stat[] = [
  { id: '1', label: 'Members', value: 500, suffix: '+', icon: 'users', display_order: 1 },
  { id: '2', label: 'Events Hosted', value: 20, suffix: '+', icon: 'calendar', display_order: 2 },
  { id: '3', label: 'Projects Built', value: 50, suffix: '+', icon: 'code', display_order: 3 },
  { id: '4', label: 'Bounties Completed', value: 100, suffix: '+', icon: 'trophy', display_order: 4 },
];

export const sampleTestimonials: Testimonial[] = [
  {
    id: '1',
    author_name: 'Builder from KL',
    author_handle: '@web3builderkl',
    author_avatar: '/images/members/placeholder.jpg',
    content: 'Superteam Malaysia helped me land my first Web3 job. The community is incredibly supportive and the events are world-class.',
    tweet_url: 'https://x.com/superteammy',
    is_featured: true,
  },
  {
    id: '2',
    author_name: 'Solana Dev MY',
    author_handle: '@solanadevmy',
    author_avatar: '/images/members/placeholder.jpg',
    content: 'Won my first hackathon through Superteam MY! The mentorship and connections are unmatched in the Malaysian Web3 scene.',
    tweet_url: 'https://x.com/superteammy',
    is_featured: true,
  },
  {
    id: '3',
    author_name: 'DeFi Builder',
    author_handle: '@defibuilder_my',
    author_avatar: '/images/members/placeholder.jpg',
    content: 'From zero Web3 experience to building on Solana in 3 months. Thank you Superteam Malaysia for making this possible!',
    tweet_url: 'https://x.com/superteammy',
    is_featured: true,
  },
];

export const sampleFAQs: FAQ[] = [
  {
    id: '1',
    question: 'What is Superteam Malaysia?',
    answer: 'Superteam Malaysia is the local chapter of the global Superteam network, dedicated to empowering builders, creators, founders, and talent in the Solana ecosystem. We support Web3 growth in Malaysia through events, education, grants, and community building.',
    display_order: 1,
  },
  {
    id: '2',
    question: 'How do I join Superteam Malaysia?',
    answer: 'You can join our community by connecting with us on Telegram, or Twitter/X. We welcome developers, designers, content creators, business developers, and anyone passionate about Web3 and Solana.',
    display_order: 2,
  },
  {
    id: '3',
    question: 'What opportunities are available?',
    answer: 'We offer bounties, grants, job opportunities, hackathons, workshops, and mentorship programs. Whether you\'re a developer, designer, or community builder, there are opportunities for you to earn and grow.',
    display_order: 3,
  },
  {
    id: '4',
    question: 'How can projects collaborate with us?',
    answer: 'If you\'re a Solana project looking to expand in Malaysia, reach out to us via our social channels. We can help with community building, talent sourcing, event partnerships, and ecosystem integration.',
    display_order: 4,
  },
  {
    id: '5',
    question: 'Do I need to be a developer to join?',
    answer: 'Absolutely not! Superteam Malaysia welcomes all skill sets — designers, content creators, marketers, business developers, community managers, and more. Web3 needs diverse talent to thrive.',
    display_order: 5,
  },
];
